Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2018-10, with the labels that each got.

#47 New Feature: OH Sysmon from OH FW & Splitting Monitoring Into Dedicated Files
  Makefile
  include/amc.h
  include/daq_monitor.h
  src/amc.cpp
  src/calibration_routines.cpp
  src/daq_monitor.cpp
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#54 New Feature: getmonOHSysmonLocal() can now read v2b sysmon values
  src/daq_monitor.cpp
Labels: Priority: High, Type: Enhancement

#53 Making use of unused in bits in dataword of DAC Scan
  Makefile
  src/amc.cpp
  src/calibration_routines.cpp
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#51 read the number of OHs from the AMC register and perform checks on the NOH rpc key
  src/amc.cpp
  src/calibration_routines.cpp
  src/daq_monitor.cpp
  src/vfat3.cpp
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#50 remove all requests for the 'ohVfatMaskArray' key
  src/vfat3.cpp
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#57 Adding memhub
  Makefile
  include/memhub.h
  include/utils.h
  src/amc.cpp
  src/calibration_routines.cpp
  src/daq_monitor.cpp
  src/extras.cpp
  src/memhub.cpp
  src/memory.cpp
  src/optohybrid.cpp
  src/utils.cpp
  src/vfat3.cpp
Labels: Priority: Critical, Status: Review Needed, Type: Enhancement

#60 Bug Fix: Removed IREF Scan and Addressing #59
  src/calibration_routines.cpp
Labels: Priority: Critical, Type: Bugfix
