Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2018-04, with the labels that each got.

#29 Refactoring, documentation and status/monitoring tools
  Makefile
  doc/ctp7_modules.doxygen
  include/optohybrid.h
  include/utils.h
  include/vfat3.h
  src/amc.cpp
  src/calibration_routines.cpp
  src/extras.cpp
  src/optohybrid.cpp
  src/utils.cpp
  src/vfat3.cpp
Labels: Priority: High, Status: Review Needed, Type: Enhancement, Type: Maintenance

#37 New Feature: Set Channel Registers
  include/vfat3.h
  src/calibration_routines.cpp
  src/vfat3.cpp
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#36 Addressing issues #34, #35 and https://github.com/cms-gem-daq-project/xhal/pull/58
  src/amc.cpp
  src/calibration_routines.cpp
Labels: Priority: Critical, Type: Bugfix
