Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2018-02, with the labels that each got.

#18 Resolve path dependency
  setup.sh
Labels: Priority: Medium, Type: Bugfix, Type: Enhancement, Type: Maintenance

#23 Bug Fix: Addresses #22
  src/utils.cpp
Labels: Priority: Critical, Status: Revision Needed, Type: Bugfix

#17 New Feature: Parallel SBIT Rate Scan vs. Arbitrary Register
  src/calibration_routines.cpp
Labels: Priority: High, Status: Completed, Type: Enhancement

#20 New Feature: genScanLocal uses current pulse mode of calibration module
  src/calibration_routines.cpp
Labels: Priority: Medium, Status: In Progress, Type: Enhancement
