Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2019-05, with the labels that each got.

#115 New Feature: Updates to DAC & GBT Phase Scans
  include/amc.h
  include/utils.h
  src/amc.cpp
  src/calibration_routines.cpp
  src/gbt.cpp
  src/utils.cpp
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement

#123 [Hotfix] v1.1.X: Fixed a bug where the trigger rate counter was cleared before it was read
  src/calibration_routines.cpp
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix, Type: Maintenance

#120 #100 : added 5 modules to read SCAADC sensors
  include/amc/sca.h
  include/amc/sca_enums.h
  include/hw_constants.h
  include/utils.h
  src/amc.cpp
  src/amc/sca.cpp
  src/utils.cpp
Labels: PR: unreviewed
