Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2019-04, with the labels that each got.

#112 Bug Fix: Bad Node Names & Hard Coded LMDB Size Limit
  include/utils.h
  src/daq_monitor.cpp
Labels: PR: reviewed-approved, Priority: Critical, Type: Bugfix

#113 [bugfix] Fix bugs introduced with LMDB cleanup
  src/utils.cpp
Labels: PR: reviewed-approved, Type: Bugfix

#99 New Feature: Adding vfatMask argument to getVFAT3ChipIDsLocal and a check for sync
  include/vfat3.h
  src/vfat3.cpp
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement
