Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2019-03, with the labels that each got.

#94 Clean up Makefile for improved build
  Makefile
Labels: PR: reviewed-approved, Priority: Medium, Type: Bugfix, Type: Enhancement

#92 Hot Fix: readVFAT3ADCLocal now uses cached registers [develop]
  src/vfat3.cpp
Labels: PR: unreviewed, Priority: Medium, Type: Bugfix, Type: Enhancement

#96 [chore] Fix warnings about signed vs. unsigned comparisons
  src/amc.cpp
  src/amc/ttc.cpp
  src/calibration_routines.cpp
Labels: PR: reviewed-approved, Priority: Low, Type: Maintenance

#98 Fix error in Makefile
  Makefile
Labels: PR: reviewed-changes-requested, Type: Bugfix

#97 SCA command control functions
  include/amc/sca.h
  include/amc/sca_enums.h
  src/amc/sca.cpp
Labels: PR: unreviewed, Priority: Medium, Type: Enhancement

#104 Hotfix for V2B scan issues
  Makefile
  src/optohybrid.cpp
Labels: Type: Bugfix

#105 Cleanup
  include/utils.h
  src/amc.cpp
  src/amc/daq.cpp
  src/amc/sca.cpp
  src/amc/ttc.cpp
  src/calibration_routines.cpp
  src/daq_monitor.cpp
  src/gbt.cpp
  src/optohybrid.cpp
  src/utils.cpp
  src/vfat3.cpp
Labels: PR: reviewed-approved

#107 [feature] BLASTER RAM interface
  Makefile
  include/amc/blaster_ram.h
  include/amc/blaster_ram_defs.h
  include/gbt.h
  include/hw_constants.h
  include/hw_constants_checks.h
  include/utils.h
  src/amc.cpp
  src/amc/blaster_ram.cpp
  src/extras.cpp
  src/utils.cpp
Labels: PR: reviewed-approved, Type: Enhancement

#110 Add a 92us sleep for the reset functions
  src/daq_monitor.cpp
Labels: PR: reviewed-approved, Priority: Critical, Type: Enhancement
