Repository cms-gem-daq-project/ctp7_modules, pull requests merged in 2019-01, with the labels that each got.

#69 New Feature: Phase Align Function
  include/amc.h
  src/amc.cpp
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed

#75 Implement RPC methods for configuring the GBTX's v2
  Makefile
  include/gbt.h
  include/hw_constants.h
  include/hw_constants_checks.h
  include/utils.h
  src/gbt.cpp
Labels: PR: unreviewed, Priority: Critical, Type: Enhancement

#81 Fixing DAC scans with cached registers for nOH != 0
  include/lmdb_cpp_wrapper.h
  src/calibration_routines.cpp
Labels: PR: reviewed-approved, Status: Blocked, Status: On Hold
